apiVersion: apps/v1
kind: Deployment
metadata:
  name: dreamlist-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dreamlist-app
  template:
    metadata:
      labels:
        app: dreamlist-app
    spec:
      containers:
      - name: flask-app
        image: bayramert/dreamlist-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: dreamlist-app-service
spec:
  selector:
    app: dreamlist-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
